version: '3.8'
services:

  # https://grafana.com/docs/agent/latest/set-up/install-agent-docker/
  daemon:
    image: grafana/agent:v0.25.1
    hostname: '{{ inventory_hostname }}'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt'
      - '{{ data_dir }}/:/etc/agent/data'
      - '{{ config_dir }}/agent.yaml:/etc/agent/agent.yaml'
      
      # exposed for various embedded-agents/integrations
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /proc:/host/proc:ro
      - /var/run:/var/run:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/log:/var/log:ro

    command: --config.file=/etc/agent/agent.yaml
    deploy:
      mode: global
      restart_policy:
        condition: any
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
